apiVersion: v2
name: unified-replication-operator
description: kubernetes-csi-addons compatible replication operator with multi-backend translation (Ceph, Trident, PowerStore)
type: application
version: 2.0.0-beta
appVersion: "2.0.0-beta"
keywords:
  - storage
  - replication
  - kubernetes-csi-addons
  - ceph
  - trident
  - powerstore
  - disaster-recovery
  - backup
  - volume-groups
home: https://github.com/unified-replication/operator
sources:
  - https://github.com/unified-replication/operator
maintainers:
  - name: Unified Replication Team
    email: team@unified-replication.io
icon: https://unified-replication.io/logo.png
kubeVersion: ">=1.24.0-0"

