---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - replication.storage.io
  resources:
  - unifiedvolumereplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.storage.io
  resources:
  - unifiedvolumereplications/finalizers
  verbs:
  - update
- apiGroups:
  - replication.storage.io
  resources:
  - unifiedvolumereplications/status
  verbs:
  - get
  - patch
  - update
