apiVersion: replication.unified.io/v1alpha2
kind: VolumeReplication
metadata:
  name: ceph-db-replication
  namespace: production
spec:
  # Reference to the VolumeReplicationClass that defines replication parameters
  volumeReplicationClass: ceph-rbd-replication
  
  # Name of the PersistentVolumeClaim to replicate
  pvcName: database-pvc
  
  # Replication state: "primary" means this volume is the primary (source)
  # Other valid values: "secondary" (replica), "resync" (force resynchronization)
  replicationState: primary
  
  # Automatically resync after connection loss and recovery
  autoResync: true

---
# Note: You'll also need a matching VolumeReplication resource in the DR site
# with replicationState: secondary to receive the replicated data
#
# apiVersion: replication.unified.io/v1alpha2
# kind: VolumeReplication
# metadata:
#   name: ceph-db-replication
#   namespace: disaster-recovery
# spec:
#   volumeReplicationClass: ceph-rbd-replication
#   pvcName: database-pvc-dr
#   replicationState: secondary
#   autoResync: true

