apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: unified-replication-staging

namePrefix: staging-

commonLabels:
  environment: staging
  app.kubernetes.io/part-of: unified-replication-operator

resources:
- ../../default

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: unified-replication-operator
    spec:
      replicas: 2
      template:
        spec:
          containers:
          - name: manager
            resources:
              limits:
                cpu: 400m
                memory: 384Mi
              requests:
                cpu: 100m
                memory: 128Mi
            args:
            - --log-level=info
            - --max-concurrent-reconciles=3
  target:
    kind: Deployment

configMapGenerator:
- name: operator-config
  literals:
  - LOG_LEVEL=info
  - CACHE_EXPIRY=5m

