apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

namespace: unified-replication-system

commonLabels:
  environment: production
  app.kubernetes.io/part-of: unified-replication-operator

resources:
- ../../default
- network-policy.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: unified-replication-operator
    spec:
      replicas: 3
      template:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      control-plane: controller-manager
                  topologyKey: kubernetes.io/hostname
          containers:
          - name: manager
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            args:
            - --log-level=info
            - --max-concurrent-reconciles=5
  target:
    kind: Deployment

configMapGenerator:
- name: operator-config
  literals:
  - LOG_LEVEL=info
  - ENABLE_AUDIT=true
  - CACHE_EXPIRY=5m
  - RECONCILE_TIMEOUT=5m

