{{- if .Values.security.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "unified-replication-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-replication-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "unified-replication-operator.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  policyTypes:
    {{- toYaml .Values.security.networkPolicy.policyTypes | nindent 4 }}
  ingress:
  # Webhook traffic from API server
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: {{ .Values.webhook.port }}
  egress:
  # DNS
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Kubernetes API server (CIDR-based, not namespace-based)
  - to:
    - podSelector: {}
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
  # Allow all HTTPS egress for storage backend APIs and Kubernetes API
  - ports:
    - protocol: TCP
      port: 443
{{- end }}

