apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified-replication-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-replication-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "unified-replication-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
---
{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified-replication-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-replication-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: {{ .Values.service.port }}
    targetPort: webhook
    protocol: TCP
  selector:
    {{- include "unified-replication-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}

