{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unified-replication-operator.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unified-replication-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: webhook
    protocol: TCP
    name: webhook
  selector:
    {{- include "unified-replication-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}

